(() => {
 const LF=window.LF, el=LF.el;
 const labels={'gallery':'Gallery','first-date':'Our First Date','story-begins':'Our Story Begins','best-part':'The Best Part','favorite':'Favorite Photos','birthday':'Birthday','family':'Family','airport':'Airport','nagarkot':'Nagarkot','videos':'Video Library','play':'Home Play Movie'};
 function button(text,action){const b=el('button',text,'lf-action');b.type='button';b.onclick=action;return b;}
 function field(form,label,type='text',value=''){const wrap=el('label',label,'lf-field'),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value;wrap.append(input);form.append(wrap);return input;}
 function dialog(title){const modal=el('dialog','','lf-editor'),heading=el('h2',title),close=button('Close',()=>modal.close());close.classList.add('lf-dialog-close');modal.append(heading,close);document.body.append(modal);modal.addEventListener('close',()=>modal.remove());modal.showModal();return modal;}
 async function refresh(){await LF.refresh();LF.render();renderLibrary();}
 LF.addMedia=collection=>{
  const modal=dialog('Add photos or videos');const form=el('form');modal.append(form);const input=field(form,'Choose files','file');input.accept='image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime';input.multiple=true;input.required=true;
  const select=el('select');for(const [id,label] of Object.entries(labels))if(id!=='play'){const option=el('option',label);option.value=id;select.append(option);}select.value=collection||'gallery';const wrap=el('label','Album','lf-field');wrap.append(select);form.append(wrap);
  const status=el('p');status.setAttribute('role','status');const save=button('Upload');save.type='submit';form.append(save,status);
  form.onsubmit=async event=>{event.preventDefault();save.disabled=true;input.disabled=true;let completed=0;try{for(const file of input.files){status.textContent=`Uploading ${file.name}…`;await LF.upload(file,select.value,null,p=>status.textContent=`${file.name}: ${p}%`);completed++;}await refresh();modal.close();LF.notify(`${completed} ${completed===1?'memory':'memories'} saved.`);}catch(error){status.textContent=`${completed} saved. ${error.message}`;await refresh();}finally{save.disabled=false;input.disabled=false;}};
 };
 LF.editMedia=item=>{
  item=LF.media(item.id)||item;
  const modal=dialog(item.deleted?'Restore memory':'Edit memory'),form=el('form');modal.append(form);
  const title=field(form,'Title','text',item.title);title.required=true;title.maxLength=200;const caption=field(form,'Caption','textarea',item.caption);caption.maxLength=5000;
  const groups=el('fieldset');groups.append(el('legend','Albums'));const checks=[];
  for(const[id,label]of Object.entries(labels)){if(id==='play'&&item.id!=='play-movie')continue;const row=el('label',label);const check=el('input');check.type='checkbox';check.value=id;check.checked=item.collections.includes(id);if(item.id==='play-movie')check.disabled=true;row.prepend(check);groups.append(row);checks.push(check);}form.append(groups);
  const replace=field(form,'Replace file (optional)','file');replace.accept=item.kind==='photo'?'image/jpeg,image/png,image/webp,image/gif':'video/mp4,video/webm,video/quicktime';
  const status=el('p');status.setAttribute('role','status');const save=button(item.deleted?'Restore and save':'Save changes');save.type='submit';form.append(save,status);
  form.onsubmit=async event=>{event.preventDefault();save.disabled=true;try{const selected=checks.filter(x=>x.checked).map(x=>x.value);if(!selected.length&&item.collections.length)throw Error('Choose at least one album.');const groups=selected.length?selected:['gallery'];if(replace.files[0])await LF.upload(replace.files[0],groups[0],item.id,p=>status.textContent=`Uploading: ${p}%`);await LF.save(`/api/media/${item.id}`,'PATCH',{title:title.value,caption:caption.value,collections:groups,restore:!!item.deleted});await refresh();modal.close();LF.notify(item.deleted?'Memory restored.':'Changes saved.');}catch(error){status.textContent=error.message;}finally{save.disabled=false;}};
  if(!item.deleted){const remove=button('Move to Recently removed',async()=>{remove.disabled=true;try{await LF.api(`/api/media/${item.id}`,{method:'DELETE'});await refresh();modal.close();LF.notify('Moved to Recently removed. You can restore it in Settings.');}catch(error){status.textContent=error.message;remove.disabled=false;}});remove.classList.add('lf-danger');modal.append(remove);}
 };
 let filter,search,library,removed;
 function renderLibrary(){if(!library)return;library.replaceChildren();const term=search.value.toLowerCase();const items=LF.state.media.filter(item=>!!item.deleted===removed.checked&&(!filter.value||item.collections.includes(filter.value))&&(`${item.title} ${item.caption}`).toLowerCase().includes(term));document.getElementById('media-total').textContent=`${items.length} ${items.length===1?'memory':'memories'}`;
  for(const item of items){const card=el('article','','lf-library-card');const preview=el(item.kind==='photo'?'img':'video');preview.src=item.url;preview.loading='lazy';preview.alt=item.title;if(item.kind==='video'){preview.controls=true;preview.preload='none';}if(!item.deleted)card.append(preview);card.append(el('h3',item.title),el('p',item.collections.map(x=>labels[x]).join(' · ')||'Profile picture'),button(item.deleted?'Restore':'Edit',()=>LF.editMedia(item)));library.append(card);}if(!items.length)library.append(el('p','No memories match this filter.'));
 }
 function settings(){const main=document.querySelector('main');const profile=LF.state.profiles.find(x=>x.id===LF.profile());
  const section=document.querySelector('.setting');section.replaceChildren(el('h2','Your profile'));const form=el('form');section.append(form);const picker=el('select');picker.setAttribute('aria-label','Switch profile');for(const p of LF.state.profiles){const option=el('option',p.name);option.value=p.id;picker.append(option);}picker.value=profile.id;form.append(picker);
  const name=field(form,'Profile name','text',profile.name);name.required=true;name.maxLength=60;const photo=field(form,'Profile picture','file');photo.accept='image/jpeg,image/png,image/webp,image/gif';const preview=el('img','','lf-avatar');preview.alt='Current profile picture';preview.hidden=!profile.picture;if(profile.picture)preview.src=profile.picture;form.append(preview);let reset=false;
  form.append(button('Reset picture',()=>{reset=true;preview.hidden=true;photo.value='';}));
  picker.onchange=()=>{localStorage.setItem('lf-active-profile',picker.value);const p=LF.state.profiles.find(x=>x.id===picker.value);name.value=p.name;preview.hidden=!p.picture;if(p.picture)preview.src=p.picture;photo.value='';reset=false;LF.render();};
  const save=button('Save profile');save.type='submit';form.append(save);const state=el('p');state.setAttribute('role','status');form.append(state);
  form.onsubmit=async event=>{event.preventDefault();save.disabled=true;try{const current=LF.state.profiles.find(x=>x.id===picker.value);let picture=reset?'':current.picture;if(photo.files[0])picture=(await LF.upload(photo.files[0],'profile',null,p=>state.textContent=`Uploading: ${p}%`)).url;await LF.save(`/api/profiles/${picker.value}`,'PATCH',{name:name.value,picture});await refresh();photo.value='';reset=false;preview.hidden=!picture;if(picture)preview.src=picture;picker.selectedOptions[0].textContent=name.value;state.textContent='Profile saved.';}catch(error){state.textContent=error.message;}finally{save.disabled=false;}};
  const dateSection=el('section','','setting');dateSection.append(el('h2','Our relationship'));const dates=el('form');dateSection.append(dates);const date=field(dates,'Together since','date',LF.state.settings.start_date);date.required=true;const timezone=field(dates,'Time zone','text',LF.state.settings.timezone);timezone.required=true;const hint=el('p','For example: Asia/Kathmandu. The anniversary countdown updates live every second.');dates.append(hint);const dateSave=button('Save date');dateSave.type='submit';const dateStatus=el('p');dateStatus.setAttribute('role','status');dates.append(dateSave,dateStatus);dates.onsubmit=async event=>{event.preventDefault();dateSave.disabled=true;try{await LF.save('/api/settings','PATCH',{start_date:date.value,timezone:timezone.value});await LF.refresh();dateStatus.textContent=`Saved. ${LF.state.counter.days.toLocaleString()} days together.`;}catch(error){dateStatus.textContent=error.message;}finally{dateSave.disabled=false;}};main.append(dateSection);
  const manager=el('section','','lf-manager');manager.id='manage-media';manager.append(el('h2','Photos & videos'),el('p','Add memories, edit captions, replace files, or restore removed items.'));const controls=el('div','','lf-manager-controls');filter=el('select');filter.setAttribute('aria-label','Filter album');const all=el('option','All albums');all.value='';filter.append(all);for(const[id,label]of Object.entries(labels)){const option=el('option',label);option.value=id;filter.append(option);}search=el('input');search.type='search';search.placeholder='Search memories';search.setAttribute('aria-label','Search memories');removed=el('input');removed.type='checkbox';const removedLabel=el('label','Recently removed');removedLabel.prepend(removed);controls.append(filter,search,removedLabel,button('＋ Add media',()=>LF.addMedia(filter.value==='play'?'gallery':filter.value)));filter.onchange=search.oninput=removed.onchange=renderLibrary;manager.append(controls);const total=el('p');total.id='media-total';library=el('div','','lf-library');library.id='media-library';manager.append(total,library);main.append(manager);renderLibrary();
  const account=el('section','','setting');account.append(el('h2','Account'),button('Sign out',async()=>{try{await LF.api('/api/logout',{method:'POST'});location.href='/login.html';}catch(error){LF.notify(error.message);}}));main.append(account);
 }
 function editing(){
  const main=document.querySelector('main')||document.body;if(!main)return;
  if(['profile.html','settings.html','favorites.html','watch.html','gallery.html'].includes(location.pathname.split('/').pop()))return;
  const page=LF.page(); const candidates=[...main.querySelectorAll('h1,h2,h3,p')].filter(node=>!node.closest('nav,footer,dialog,.relationship-counter,.lf-card,.lf-album,.lf-photo,.lf-memory,.photo-lightbox')&&!node.querySelector('input,button,img,video'));
  candidates.forEach((node,index)=>{node.dataset.editId=`text-${index}`;});
  for(const record of LF.state.content.filter(x=>x.page===page)){let node=main.querySelector(record.selector);if(!node&&record.selector.includes('custom-')){node=el('p');node.dataset.editId=record.selector.match(/"([^"]+)"/)[1];main.append(node);candidates.push(node);}if(node)node.textContent=record.text;}
  const bar=el('div','','lf-edit-bar'),edit=button('Edit page text'),save=button('Save text'),cancel=button('Cancel'),add=button('Add paragraph');save.hidden=cancel.hidden=add.hidden=true;bar.append(edit,save,cancel,add);document.body.append(bar);let originals;
  const stop=()=>{candidates.forEach(node=>{node.removeAttribute('contenteditable');node.classList.remove('lf-editing');});save.hidden=cancel.hidden=add.hidden=true;edit.hidden=false;};
  edit.onclick=()=>{originals=new Map(candidates.map(node=>[node,node.textContent]));candidates.forEach(node=>{node.contentEditable='plaintext-only';node.classList.add('lf-editing');});save.hidden=cancel.hidden=add.hidden=false;edit.hidden=true;LF.notify('Edit the highlighted text. Clear a field to remove its text, then save.');};
  add.onclick=()=>{const node=el('p','Write your new paragraph here.');node.dataset.editId=`custom-${crypto.randomUUID()}`;node.contentEditable='plaintext-only';node.classList.add('lf-editing');main.append(node);candidates.push(node);originals.set(node,null);node.focus();};
  cancel.onclick=()=>{for(const[node,text]of originals){if(text===null){node.remove();candidates.splice(candidates.indexOf(node),1);}else node.textContent=text;}stop();};
  save.onclick=async()=>{save.disabled=true;try{for(const node of candidates){if(node.textContent!==originals.get(node))await LF.save('/api/content','PUT',{page,selector:`[data-edit-id="${node.dataset.editId}"]`,text:node.textContent});}stop();LF.notify('Page text saved.');}catch(error){LF.notify(error.message);}finally{save.disabled=false;}};
 }
 LF.ready.then(()=>{if(!LF.state)return;if(location.pathname.endsWith('settings.html'))settings();else editing();});
})();
