const favoriteData = {
  love: { title: '❤️ Things I Love About You', html: '<ul class="favorite-list"><li><b>Your understanding nature</b> — you listen, you care, and you always try to understand me.</li><li><b>The way you handle me</b> — especially through all my moodswings, with so much patience and love.</li><li><b>The way you are</b> — genuine, comforting, and completely yourself.</li><li><b>How you fulfill my dreams and promises</b> — you make me feel supported and safe in our future.</li><li><b>Your loyalty</b> — one of the most beautiful things about your heart.</li><li><b>The gentleman you are</b> — your respect, care, and the little things you do mean everything to me.</li></ul>' },
  songs: { title: '🎵 Your Favorite Songs', html: '<p class="favorite-note">Press play—the music plays directly here through Spotify.</p><div class="embedded-songs spotify-songs"><section><strong>Tum Se Hi</strong><iframe src="https://open.spotify.com/embed/track/7eQl3Yqv35ioqUfveKHitE?utm_source=generator" title="Tum Se Hi Spotify player" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></section><section><strong>Sahiba — Vijay Deverakonda & Radhikka Madan</strong><iframe src="https://open.spotify.com/embed/track/4ulroyDK6rN73nVkCkWhur?utm_source=generator" title="Sahiba featuring Vijay Deverakonda Spotify player" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></section><section><strong>Thodi Der</strong><iframe src="https://open.spotify.com/embed/track/5h4HUJcttHP0EuMLLdfXyO?utm_source=generator" title="Thodi Der Spotify player" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></section></div>' },
  things: { title: '🍔 Your Favorite Foods', html: '<div class="food-choice-grid"><figure><img src="https://images.deliveryhero.io/image/fd-bd/LH/p2ic-listing.jpg" alt="Steamed momo with dipping sauce"><figcaption>Chicken Momo</figcaption></figure><figure><img src="https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80" alt="Chicken dish"><figcaption>Chicken</figcaption></figure><figure><img src="https://images.unsplash.com/photo-1622708862830-a026e3ef60bd?auto=format&fit=crop&w=700&q=80" alt="A Coca-Cola bottle"><figcaption>Coca-Cola</figcaption></figure><figure><img src="https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=700&q=80" alt="A chicken roll wrap"><figcaption>Chicken Roll</figcaption></figure><figure><img src="https://i0.wp.com/www.onceuponachef.com/images/2023/04/tiramisu.jpg?ssl=1&w=1583" alt="A slice of tiramisu"><figcaption>Tiramisu</figcaption></figure></div>' },
  you: { title: '🏆 My Favorite You', html: '<p class="favorite-note">My favorite version of you is every version: smiling, laughing, being yourself, and living your beautiful life.</p><div class="favorite-photo-grid"><img src="images/us-1.jpeg" alt="Favorite photo of you"><img src="images/us-3.jpeg" alt="Favorite photo of you"><img src="images/us-15.jpeg" alt="Favorite photo of you"><img src="images/us-17.jpeg" alt="Favorite photo of you"><img src="images/us-19.jpeg" alt="Favorite photo of you"><img src="images/us-23.jpeg" alt="Favorite photo of you"><img src="images/us-30.jpeg" alt="Favorite photo of you"><img src="images/us-32.jpeg" alt="Favorite photo of you"></div>' }
};

const favoriteDialog = document.querySelector('.favorite-dialog');
const favoriteClose = document.querySelector('.favorite-close');
document.querySelectorAll('.favorite-card').forEach((card) => card.addEventListener('click', () => {
  const item = favoriteData[card.dataset.favorite];
  document.querySelector('#favorite-title').textContent = item.title;
  document.querySelector('.favorite-content').innerHTML = item.html;
  favoriteDialog.showModal();
  favoriteClose.focus();
}));
favoriteClose.addEventListener('click', () => favoriteDialog.close());
favoriteDialog.addEventListener('click', (event) => { if (event.target === favoriteDialog) favoriteDialog.close(); });
