CREATE SCHEMA IF NOT EXISTS loveflix;
SET LOCAL search_path TO loveflix;
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,salt TEXT NOT NULL,password TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS profiles(id TEXT PRIMARY KEY,name TEXT NOT NULL,picture TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,original TEXT NOT NULL,path TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,caption TEXT NOT NULL DEFAULT '',collections TEXT NOT NULL,deleted INTEGER NOT NULL DEFAULT 0,revision INTEGER NOT NULL DEFAULT 1,created DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS favorites(profile TEXT NOT NULL,id TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(profile,id));
CREATE TABLE IF NOT EXISTS content(page TEXT NOT NULL,selector TEXT NOT NULL,text TEXT NOT NULL,PRIMARY KEY(page,selector));
CREATE TABLE IF NOT EXISTS login_attempts(key TEXT PRIMARY KEY,started DOUBLE PRECISION NOT NULL,attempts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pending_uploads(id TEXT PRIMARY KEY,token TEXT NOT NULL,path TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,collection TEXT NOT NULL,media_id TEXT,size BIGINT NOT NULL,expires DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
CREATE INDEX IF NOT EXISTS pending_expiry ON pending_uploads(expires);
-- This schema is used only through the authenticated Python backend.
REVOKE ALL ON SCHEMA loveflix FROM PUBLIC;

CREATE TABLE IF NOT EXISTS account_details(user_id BIGINT PRIMARY KEY REFERENCES users(id),name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,phone TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS password_resets(token TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id),expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS account_sessions(token TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id));
CREATE TABLE IF NOT EXISTS auth_requests(key TEXT PRIMARY KEY,started DOUBLE PRECISION NOT NULL,attempts INTEGER NOT NULL);
